### ISSUE TITLE
ModuleNotFoundError: No module named 'auxiliary.raytracer.RayTracerCython'

### ISSUE THREAD

**Issue by saltoricristiano** [PRBonn/lidar_transfer#1]
Hi all, 

thank you very much for sharing your amazing work!
I cloned your repo and installed all the required dependencies, but unfortunately while running `python lidar_deform.py -d minimal` I get the error `ModuleNotFoundError: No module named 'auxiliary.raytracer.RayTracerCython'`, namely:

<img width="690" alt="Screenshot 2021-02-15 at 12 13 06" src="https://user-images.githubusercontent.com/56728964/107939541-2d86a900-6f87-11eb-9826-a33f040f6cfc.png">

Any suggestion?
FYI: I'm running everything inside a docker NVIDIA NGC container

Thank you in advance!

**Comment by jbehley** [comment]
Hi @saltoricristiano,

we forgot one step in our description, you have to go to the folder `auxiliary/raytracer` and call there `make`. I extended the instructions in the README to include this small missing detail.

Hope that helps. Regarding the docker container, we tested the code in Ubuntu 20.04 and I think @ferdiflash used MacOS.

Let us know if you encounter other problems.

**Comment by saltoricristiano** [comment]
Hi @jbehley, 

thanks for your suggestion! Unfortunately by running `make` in `auxiliary/raytracer` I get:

<img width="859" alt="Screenshot 2021-02-17 at 11 23 57" src="https://user-images.githubusercontent.com/56728964/108190989-eaf1d780-7112-11eb-88b9-0bc6aa74f3ef.png">

Any suggestion?
My Cython version is 0.28.4 and make 4.1.

**Comment by jbehley** [comment]
Strange, with my version it silently accepts the string as an argument. I changed it to int, thus, it should now compile.

**Comment by saltoricristiano** [comment]
Hi,

I started a new pristine docker container from `nvcr.io/nvidia/pytorch:21.02-py3` and the error disappeared.
Thanks for the suggestions!
Going o close this issue!

**Comment by vijayM12** [comment]
@jbehley @saltoricristiano I have tried to reproduce the repo and I am getting the following error while running make. Please help me to successfully execute the repo
![error ](https://user-images.githubusercontent.com/93333400/208292702-2779c12f-1334-4b56-9286-922ad1b3f26b.png)

![error1](https://user-images.githubusercontent.com/93333400/208292686-d00ab951-128f-47a2-8bdf-89a26821ccbc.png)

**Comment by jbehley** [comment]
Apparently, you are using Windows for compiling the C code. We currently only tested and can provide support for Ubuntu 18.04.

Please, open an own issue if you think that it's needed.

**Comment by vijayM12** [comment]
Hello @jbehley I have tried the same in google colab with ubuntu 18.04 environment and the make file executed. But, the same error is coming. Please help regarding this
![colaberror](https://user-images.githubusercontent.com/93333400/208301943-618fa1d7-0117-4970-9910-caa95b5702a8.png)
