### ISSUE TITLE
How do I convert VLS128 to HDL64

### ISSUE THREAD

**Issue by nakaotatsuya** [PRBonn/lidar_transfer#3]
Thank you very much for your work.
But I am not clear about how to convert tha data of VLS128 to that of HDL64.

from the link below, I can know that rays are not lined up at equal intervals in the VLS128 lidar (unlike the HDL64)
https://perceptionengine.jp/blog/autoware/lidar-laser-distributions/

I prepared target and source yaml files respectively and implemented lidar_deform.py, but I couldn't get the good result.
Is it difficult to convert between HDL64 and VLS128?

**Comment by vijayM12** [comment]
Hello @nakaotatsuya I appreciate your interest in this. I would like to convert synthetic point cloud data to Velodyne real kitti data.  I am having issue in implementing lidar_deform.py. Could you please help in this conversion whether it is possible using this repo.
